# Generated by Django 5.0.7 on 2024-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='duolingo',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='ielts',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='sat',
        ),
        migrations.AddField(
            model_name='certificates',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificates',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
