# Generated by Django 5.0.7 on 2024-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_certificates_duolingo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='score',
            field=models.FloatField(),
        ),
    ]
