# Generated by Django 5.0.7 on 2024-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_certificates_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
